services:
  - type: web
    name: geronimo-ai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        value: YOUR_API_ID
      - key: API_HASH
        value: YOUR_API_HASH
      - key: BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
